# Generated by Django 3.2.5 on 2021-07-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
