# Generated by Django 3.2.5 on 2021-07-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articles_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='views',
        ),
    ]
