# Generated by Django 3.2.5 on 2021-07-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_articles_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journalists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('suername', models.CharField(max_length=250)),
                ('biography', models.TextField()),
            ],
        ),
    ]
